version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: adoption_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: Callejeros_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adoption.api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: adoption_api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=adoptiondb;Username=postgres;Password=12345678"
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata:
